export const ACTIONS = {
  ADD_TODO: 'ADD_TODO',
  COMPLETE: 'COMPLETE',
  DELETE: 'DELETE',
  SHOW_DATE: 'SHOW_DATE',
  CHECK: 'CHECK',
  DELETE_ALL: 'DELETE_ALL',
  COMPLETE_ALL: 'COMPLETE_ALL',
};
